apiVersion: batch/v1
kind: Job
metadata:
  name: my-app-job
  labels:
    app: my-app
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: my-app:1.0.0
          imagePullPolicy: IfNotPresent
          args:
            - /bin/sh
            - -c
            - |
              date
              echo "Hello from the Kubernetes cluster"
      restartPolicy: OnFailure
