apiVersion: v1
kind: Pod
metadata:
  name: my-app-multicontainer
  labels:
    app: my-app
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  containers:
    - name: app-container
      image: my-app:1.0.0
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/app
    - name: log-sidecar
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args:
        - tail -n+1 -F /var/log/app/app.log
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/app
